// ISO 3166-1 alpha-2 -> display name, for the country filter and map tooltips.
// Covers every code that appears in the data plus common others; unknown codes
// fall back to the raw code via countryName().
export const COUNTRY_NAME: Record<string, string> = {
  US: "United States",
  GB: "United Kingdom",
  CA: "Canada",
  JP: "Japan",
  FR: "France",
  DE: "Germany",
  AU: "Australia",
  CN: "China",
  IT: "Italy",
  KR: "South Korea",
  NZ: "New Zealand",
  IE: "Ireland",
  BE: "Belgium",
  SE: "Sweden",
  HK: "Hong Kong",
  ES: "Spain",
  IN: "India",
  AE: "United Arab Emirates",
  MX: "Mexico",
  AT: "Austria",
  HU: "Hungary",
  CZ: "Czech Republic",
  BG: "Bulgaria",
  DK: "Denmark",
  ZA: "South Africa",
  CH: "Switzerland",
  NO: "Norway",
  AR: "Argentina",
  NL: "Netherlands",
  TH: "Thailand",
  FI: "Finland",
  IS: "Iceland",
  BR: "Brazil",
  IL: "Israel",
  VN: "Vietnam",
  HR: "Croatia",
  TR: "Turkey",
  RU: "Russia",
  RS: "Serbia",
  CO: "Colombia",
  JO: "Jordan",
  KH: "Cambodia",
  SG: "Singapore",
  MA: "Morocco",
  PL: "Poland",
  PT: "Portugal",
  ID: "Indonesia",
  BS: "Bahamas",
  MT: "Malta",
  KY: "Cayman Islands",
  SN: "Senegal",
  RO: "Romania",
  CR: "Costa Rica",
  GR: "Greece",
  GM: "Gambia",
  LU: "Luxembourg",
  SA: "Saudi Arabia",
  MY: "Malaysia",
  EG: "Egypt",
  UA: "Ukraine",
  TW: "Taiwan",
  BD: "Bangladesh",
  CL: "Chile",
  PE: "Peru",
  PH: "Philippines",
  IR: "Iran",
  PK: "Pakistan",
};

export function countryName(iso: string): string {
  return COUNTRY_NAME[iso] ?? iso;
}
