import type { Metadata } from "next";
import { Geist, Bricolage_Grotesque, Space_Mono } from "next/font/google";
import dataset from "../../public/data/cinemetrics.json";
import { datasetCounts, summaryLine } from "@/lib/summary";
import { ThemeProvider } from "@/lib/theme";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const display = Bricolage_Grotesque({ variable: "--font-display", subsets: ["latin"] });
const mono = Space_Mono({ variable: "--font-mono", subsets: ["latin"], weight: ["400", "700"] });

// Derived from the dataset, not written by hand: the description used to say
// "Seven years" long after the log reached eight. See lib/summary.
const { years, filmCount } = datasetCounts(dataset);
const DESCRIPTION = summaryLine(years, filmCount);

const OG_ALT = `cinemetrics: ${DESCRIPTION}`;

// The card is generated by app/og.png/route.tsx. Referenced by hand rather than
// via the `opengraph-image` file convention, because that convention exports an
// extensionless file under `output: "export"` and GitHub Pages types responses
// by extension - see the note in that route.
//
// metadataBase keeps its trailing slash, and the image path stays relative with
// no leading slash, so URL resolution preserves the /cinemetrics base path.
export const metadata: Metadata = {
  metadataBase: new URL("https://featheranalytics.dev/cinemetrics/"),
  title: "cinemetrics",
  description: DESCRIPTION,
  openGraph: {
    title: "cinemetrics",
    description: DESCRIPTION,
    type: "website",
    images: [{ url: "og.png", width: 1200, height: 630, alt: OG_ALT }],
  },
  twitter: {
    card: "summary_large_image",
    title: "cinemetrics",
    description: DESCRIPTION,
    images: [{ url: "og.png", alt: OG_ALT }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${display.variable} ${mono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
